server:
  port: 8010
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8000/oauth/token_key
    client:
      client-id: admin
      client-secret: 123456
spring:
  application:
    name: security-service

